name: Run Notion Script

on:
  schedule:
    - cron: '0 0 * * *'  # Täglich um Mitternacht

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Test
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        DATABASE_A_ID: ${{ secrets.DATABASE_A_ID }}
        DATABASE_B_ID: ${{ secrets.DATABASE_B_ID }}
      run: echo "my keys are Notion ${{NOTION_API_KEY}} , A- ${{DATABASE_A_ID}}, B- ¢{{DATABASE_B_ID}}

    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        DATABASE_A_ID: ${{ secrets.DATABASE_A_ID }}
        DATABASE_B_ID: ${{ secrets.DATABASE_B_ID }}

    - name: Run script
      
      run: |
        python app.py
